In [2]:
c = int(input('enter celcius = '))
d = (c*1.8) + 32
print(d)
    

enter celcius = 38
100.4


In [3]:
import re
j = '#Yash7746'
while j:
    if not re.search('[a-z]',j):
        print('invalid')
        break
    elif not re.search('[0-9]',j):
        print('invalid')
        break
    elif not re.search('[#$@&*%!^?:]',j):
        print('invalid')
        break
    elif not (len(j)<=16 and len(j)>=6):
        print('invalid')
    else:
        print('valid password')
        break

valid password


In [4]:
c = list(range(2,13))

In [5]:
import numpy as np
d = np.array(c)
print(d)

[ 2  3  4  5  6  7  8  9 10 11 12]


In [6]:
np.mean(c)

7.0

In [7]:
np.median(c)

7.0

In [8]:
np.sum(c)

77

In [9]:
np.std(c)

3.1622776601683795

In [10]:
f = np.random.random([10])

In [11]:
f

array([0.75014094, 0.40185582, 0.41076754, 0.81643853, 0.41621689,
       0.73462039, 0.46045236, 0.52012715, 0.73621455, 0.68281952])

In [12]:
f.sort()

In [13]:
f

array([0.40185582, 0.41076754, 0.41621689, 0.46045236, 0.52012715,
       0.68281952, 0.73462039, 0.73621455, 0.75014094, 0.81643853])

In [14]:
from numpy import random
g = random.randint(100, size = (10))
print(g)

[23 31 86  4 98 58 72 93 44 63]


In [15]:
k = random.randint(100, size = (2,4))
print(k)

[[64 86 31  6]
 [ 2 36 91 59]]


In [16]:
np.mean(g)

57.2

In [17]:
np.median(g)

60.5

In [18]:
np.std(g)

29.81543224573476

In [19]:
# generate a randon 1-D array of 15 numbers with help of random.randint and calculate the std deviation

In [20]:
v = random.randint(50, size=(15))
print(v)

[35  6 44 29 18 42  6  8 47  6 43  8 42 21 17]


In [21]:
np.std(v)

15.604272919086405

In [22]:
# homework: generate a randon 1-D array of 23 numbers with help of random.randint and use aggregate function on it

In [23]:
h = random.randint(100, size=(23))
print(h)

[93 58 51 35 81 62 58 55 32 61 21 86 34 62 82 67 99 71 63 36 87 28 25]


In [24]:
np.std(h)

22.482507377875343

In [25]:
np.mean(h)

58.56521739130435

In [26]:
np.median(h)

61.0

In [27]:
np.sum(h)

1347

In [28]:
np.max(h)

99

In [29]:
np.min(h)

21

In [30]:
import numpy as np
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d[0, 1, 2])

6


In [31]:
for check in arr3d:
    print(check)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [32]:
arr3d.ndim

3

In [33]:
arr3d.size

12

In [34]:
arr3d[-1, -1, -1]

12

# Homework
Declare two 2-D array and perform below menioned operations:
- addition
- Subtraction
- Multiplication
- Reshape
- Flattening of array
- Mean, median & std deviation
sort

In [35]:
ar1 = np.array([[1,2,4,7],[4,2,9,7]])
ar2 = np.array([[5,6,3,4],[7,9,2,6]])

In [36]:
print(ar1 + ar2)

[[ 6  8  7 11]
 [11 11 11 13]]


In [37]:
print(ar1-ar2)

[[-4 -4  1  3]
 [-3 -7  7  1]]


In [38]:
print(ar1*ar2)

[[ 5 12 12 28]
 [28 18 18 42]]


In [39]:
ar1.reshape(4,2)

array([[1, 2],
       [4, 7],
       [4, 2],
       [9, 7]])

In [40]:
ar2.reshape(8,1)

array([[5],
       [6],
       [3],
       [4],
       [7],
       [9],
       [2],
       [6]])

In [41]:
ar1.reshape(-1)

array([1, 2, 4, 7, 4, 2, 9, 7])

In [42]:
ar2.reshape(-1)

array([5, 6, 3, 4, 7, 9, 2, 6])

In [43]:
print(np.mean(ar1))

4.5


In [44]:
print(np.mean(ar2))

5.25


In [45]:
print(np.median(ar1))

4.0


In [46]:
print(np.median(ar2))

5.5


In [47]:
print(np.std(ar1))

2.692582403567252


In [48]:
print(np.std(ar2))

2.1065374432940898


In [49]:
print(np.sort(ar1))

[[1 2 4 7]
 [2 4 7 9]]


In [50]:
print(np.sort(ar2))

[[3 4 5 6]
 [2 6 7 9]]
