In [1]:
#create three class - and define properties/attributes + functionality and use inheritance concept

In [18]:
class C_gov():
    name = 'modi'
    def __init__(self,leader):
        self.leader = leader
    def vote(self):
        print('voted')
class S_gov(C_gov):
    def __init__(self,state):
        self.state = state
    def remove(self):
        print('removed')
class L_gov(S_gov,C_gov):
    def __init__(self,locality):
        self.locality = locality
    def kill(self):
        print('killed')




In [20]:
myob = L_gov('whitefield')

In [21]:
myob.name

'modi'

In [2]:
thiscgov = C_gov('modi')

In [3]:
thiscgov.leader

'modi'

In [4]:
thiscgov.vote()

voted


In [5]:
thislgov = L_gov('whitefield')

In [15]:
thislgov.name

removed


In [7]:
thissgov = S_gov('karnataka')

In [8]:
thissgov.remove()

removed


In [22]:
#create a class called animals and create functionalities and properties

In [90]:
class animals():
    def __init__(self,animal,species):
        self.animal = animal
        self.species = species
    def pat(self,pat):
        self.action = pat
        print('patted',pat)
class cat(animals):
    def __init__(self,colour,nickname):
        self.colour = colour
        self.nickname = nickname
    def hold(self,name):
        self.action = name
        print('held',name)

In [91]:
hamy = animals('hamster','syrian')
mo = animals('hamster','russian dwarf')

In [92]:
hamy.animal

'hamster'

In [93]:
mo.species

'russian dwarf'

In [94]:
mo.pat('mo')

patted mo


In [95]:
boris = cat('black','comrade cat')

In [97]:
boris.hold('artyom')

held artyom


In [100]:
boris.pat('cat')

patted cat


In [2]:
import numpy

In [3]:
a = numpy.array([1,3,2,4,9])
c = numpy.array([3,7,6,3,5])     #this is 1D

In [4]:
print(a+c)

[ 4 10  8  7 14]


In [5]:
print(a*c)

[ 3 21 12 12 45]


In [6]:
print(a-c)

[-2 -4 -4  1  4]


In [7]:
print(a/c)

[0.33333333 0.42857143 0.33333333 1.33333333 1.8       ]


In [9]:
#confirm operations with 2D arrays.

In [15]:
f = numpy.array([[1,2,3,4,5],[6,7,8,9,10]])
n = numpy.array([[5,6,3,5,2],[4,2,9,4,2]])

In [16]:
print(f+n)

[[ 6  8  6  9  7]
 [10  9 17 13 12]]


In [17]:
print(f-n)

[[-4 -4  0 -1  3]
 [ 2  5 -1  5  8]]


In [18]:
print(f*n)

[[ 5 12  9 20 10]
 [24 14 72 36 20]]


In [19]:
print(f/n)

[[0.2        0.33333333 1.         0.8        2.5       ]
 [1.5        3.5        0.88888889 2.25       5.        ]]


In [2]:
import numpy

In [3]:
g = numpy.arange(0,1000,100)

In [4]:
print(g)

[  0 100 200 300 400 500 600 700 800 900]


In [5]:
g.size

10

In [6]:
g.reshape(2,5)

array([[  0, 100, 200, 300, 400],
       [500, 600, 700, 800, 900]])

In [7]:
fh = numpy.array([5,1,3,7,2,8])

In [8]:
fh[4]

2

In [9]:
fh[2:5]

array([3, 7, 2])

In [14]:
sh = numpy.array([[5,2,6,3,7],[4,2,7,8,9]])

In [15]:
sh[0,1]

2

In [16]:
sh[1,4]

9