In [3]:
class A:
    def feature1(self):
        print('fetaure 1 works')
    def feature2(self):
        print('feature 2 works')
class B(A):
    def feature3(self):
        print('feature 3 works')
    def feature4(self):
        print('feature 4 works')
a1 = A()
b1 = B()

a1.feature1()
a1.feature2()
b1.feature1()
b1.feature2()
b1.feature3()
b1.feature4()

fetaure 1 works
feature 2 works
fetaure 1 works
feature 2 works
feature 3 works
feature 4 works


In [4]:
class A:
    def feature1(self):
        print('fetaure 1 works')
    def feature2(self):
        print('feature 2 works')
class B(A):
    def feature3(self):
        print('feature 3 works')
    def feature4(self):
        print('feature 4 works')
class C(B):
    def feature5(self):
        print('feature 5 works')
        
c1 = C()
c1.feature5()

feature 5 works


In [5]:
class Complex():
    def __init__(self, r, i):
        self.real = r
        self.img = i
    
        def __add__(self, sec):
            r = self.real + sec.real
            i = self.img + sec.img
            return Complex(r,i)

In [6]:
c1 = Complex(5,8)
c2 = Complex(8,2)

In [8]:
prices = {'pen' : 10, 'pencil' : 5, 'batman' : 55}
item = input('get price of: ')
if item == 'batman':
    raise KeyError('batman')
print(f'the price of {item} is {prices[item]}')

get price of: pencil
the price of pencil is 5


In [9]:
prices = {'pen' : 10, 'pencil' : 5, 'batman' : 55}
item = input('get price of: ')
if item == 'batman':
    raise KeyError('batman')
print(f'the price of {item} is {prices[item]}')

get price of: batman


KeyError: 'batman'

In [11]:
try:
    import math
    print(math.exp(1000))
except OverflowError:
    print('overflow error raised')
else:
    print('success, no error')

overflow error raised


In [14]:
try:
    a = 100
    b = 'codinghero'
    assert a == b
except AssertionError:
    print('asserion exception raised')
else:
    print('no error')

asserion exception raised


In [21]:
class Attributes():
    a = 2
    print(a)
    
try:
    object = Attributes()
    print(object.Attribute)
except AttributeError:
    print('error attribute')

2
error attribute


In [1]:
#DESIGN A PROGRAM USING FUNCTIONS IN PYTHON. 
#P = 5,00,000,  RATE = 8% ,  TERM = 30YRS

In [2]:
def simple_interest(p,rate,term):
    full = p*rate*term
    interest = full/100
    amount = p + interest
    print('interest is  ',interest)
    print('amount is ',amount)

In [3]:
simple_interest(500000,8,30)

interest is   1200000.0
amount is  1700000.0


In [36]:
def compound_interest(p,r,t):
    amount = p * (pow((1 + r / 100), t))
    interest = amount - p
    print(amount)
compound_interest(float(input('enter principal ')),float(input('enter rate ')),float(input('enter term ')))

enter principal 1000
enter rate 10
enter term 3
1331.0000000000005


In [1]:
class animals():
    def __init__(self,animal,features):
        self.animal = animal
        self.features = features
    def pat(self):
        print('patted')
class dog(animals):
    def __init__(self,breed):
        self.breed = breed
    def bark(self):
        print('barked')
class cat(animals):
    def __init__(self,colour):
        self.colour = colour
    def meow(self):
        print('meowed')
sugar = dog('honey')
puchi = cat('ginger')

In [2]:
sugar.breed

'honey'

In [3]:
puchi.meow()

meowed


In [6]:
import math
x = 9.9
math.ceil(x)

10

In [8]:
import numpy 
b = numpy.array([1,3,4])
print(b)

[1 3 4]


In [9]:
n = numpy.ones(5)

In [10]:
print(n)

[1. 1. 1. 1. 1.]


In [11]:
type(n)

numpy.ndarray

In [12]:
type(b)

numpy.ndarray

In [17]:
a = numpy.array([1,3,2,4,9])
c = numpy.array([3,7,6,3,5])     #this is 1D

In [15]:
print(a+c)

[ 4 10  8  7 14]


In [16]:
print(a*c)

[ 3 21 12 12 45]


In [18]:
print(a-c)

[-2 -4 -4  1  4]


In [19]:
print(a/c)

[0.33333333 0.42857143 0.33333333 1.33333333 1.8       ]


# 2D array

In [20]:
f = ([[1,2,3,4,5],[6,7,8,9,10]])

In [2]:
import numpy
b = numpy.array([[1,4,3,8,1],[3,8,3,8,2]])
n = numpy.array([[5,7,2,7,3]])

In [3]:
b

array([[1, 4, 3, 8, 1],
       [3, 8, 3, 8, 2]])

In [4]:
#np.linspace(start no.,end no., points)

In [5]:
v = numpy.linspace(0,150,6)

In [6]:
print(v)

[  0.  30.  60.  90. 120. 150.]


In [7]:
#np.arange(start no. , end no., intervals/tables of)

In [8]:
h = numpy.arange(10,101,15)
print(h)

[ 10  25  40  55  70  85 100]


In [12]:
h.size

6

In [13]:
b.size

10

In [14]:
print(b)

[[1 4 3 8 1]
 [3 8 3 8 2]]


In [20]:
b.reshape(2,5)    #reshaping the arrays

array([[1, 4, 3, 8, 1],
       [3, 8, 3, 8, 2]])

In [1]:
import numpy

In [2]:
df = numpy.array([1,2,3,4,5])

In [3]:
df[3]

4

In [4]:
df[1:4]

array([2, 3, 4])

In [5]:
ad = numpy.array([[1,4,3,8,1],[3,8,3,8,2]])

In [6]:
ad[0,1]

4

In [7]:
ad[1,3]

8

In [9]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
for g in ad:
    print(g)

[1 4 3 8 1]
[3 8 3 8 2]


In [17]:
h = ad.reshape(10,1)

In [18]:
for j in h:
    print(j)

[1]
[4]
[3]
[8]
[1]
[3]
[8]
[3]
[8]
[2]


In [2]:
import numpy
arr = numpy.array([1,2,3,4])
a = arr.copy()
arr[0] = 34
print(arr)
print(a)

[34  2  3  4]
[1 2 3 4]


In [9]:
b = a.view()

In [10]:
print(b)

[1 2 3 4]


In [14]:
import numpy as np
ar1 =  np.array([1,2,3,4])
x =  ar1.view()
ar1[0] = 34
print(ar1)
print (x)

[34  2  3  4]
[34  2  3  4]


In [15]:
ar2 = np.array([[1,2,4,5,3],[4,5,2,6,3]])
new_ar2 = ar2.reshape(5,2)

In [16]:
new_ar2

array([[1, 2],
       [4, 5],
       [3, 4],
       [5, 2],
       [6, 3]])

In [17]:
new_ar3 = new_ar2.reshape(-1)

In [18]:
new_ar3

array([1, 2, 4, 5, 3, 4, 5, 2, 6, 3])

In [19]:
ar2.ndim

2

In [20]:
new_ar3.ndim

1

In [21]:
for check in new_ar3:
    print(check)

1
2
4
5
3
4
5
2
6
3


In [22]:
for check in new_ar2:
    print(check)

[1 2]
[4 5]
[3 4]
[5 2]
[6 3]


In [30]:
new_ar4 = ([5,4,6,1,5,7,8,0,8,7])

In [31]:
new_ar5 = new_ar4 + new_ar3

In [32]:
new_ar5

array([ 6,  6, 10,  6,  8, 11, 13,  2, 14, 10])

In [35]:
ar3 = np.concatenate((new_ar3,new_ar4))

In [36]:
ar3

array([1, 2, 4, 5, 3, 4, 5, 2, 6, 3, 5, 4, 6, 1, 5, 7, 8, 0, 8, 7])

# Aggregate functions

In [15]:
a = list(range(1,101))

In [16]:
import numpy as np
b = np.array(a)

In [23]:
np.mean(b)

50.5

In [24]:
np.median(b)

50.5

In [25]:
np.max(b)

100

In [26]:
np.min(b)

1

In [28]:
np.std(b)

28.86607004772212

In [29]:
np.sum(b)

5050

In [1]:
from numpy import random
g = random.randint(100, size = (10))
print(g)

[13 47 25  4 32 74 92 13 57 44]


In [2]:
k = random.randint(100, size = (2,4))
print(k)

[[92 29 50 85]
 [32 91 11 23]]


In [4]:
import numpy as np
arr1 = np.array([1,6,4,9,3,9,4,32,9])
x = np.where(arr1 == 9)
print(x)

(array([3, 5, 8], dtype=int64),)


In [8]:
arr2 = np.array([5,9,6,8,2])
v = np.where(arr2%2 == 0)
print(v)

(array([2, 3, 4], dtype=int64),)


# searchsorted

In [17]:
arr3 = np.array([6,7,8,9])
x = np.searchsorted(arr3, 7)
print(x)

1


In [12]:
arr3 = np.array([6,7,8,9])
x = np.searchsorted(arr3, 7, side='right')
print(x)

2


In [20]:
arr4 = np.array([1,3,5,7])
x = np.searchsorted(arr4, [2,4,6])
print(x)

[1 2 3]


In [22]:
arr5 = np.array([1,3,9,0,13])
print(np.sort(arr5))

[ 0  1  3  9 13]


In [27]:
arr = np.array([21,22,23,24])
x = [True,False,True,False]
newarr = arr[x]
print(newarr)

[21 23]


In [30]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d[0, 1, 2])

6


In [31]:
for check in arr3d:
    print(check)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [33]:
arr3d.ndim

3

In [37]:
arr3d.size

12

In [38]:
arr3d[-1, -1, -1]

12